__all__ = ["YamlableBase"]

class YamlableBase:
    def as_yaml_string(self: YamlableBase) -> str: ...
    def as_yaml_file(self: YamlableBase, yaml_file: str) -> None: ...
    def from_yaml_string(self: YamlableBase, yaml_string: str) -> None: ...
    def from_yaml_file(self: YamlableBase, yaml_file: str) -> None: ...
