macro(erl_config_tracy)
    option(ERL_USE_TRACY "Use Tracy Profiler" OFF)
    option(ERL_TRACY_PROFILE_MEMORY "Profile memory usage" OFF)
    if (ERL_USE_TRACY)
        set(TRACY_ENABLE ON)
        if (ERL_TRACY_PROFILE_MEMORY)
            add_compile_definitions(ERL_TRACY_PROFILE_MEMORY)
        endif ()
    endif ()
endmacro()
